### PR TITLE
chore: restructure hooks folder

### PR DESCRIPTION
**Pull request by dlnanh85**
- Add `index.ts` to `src/hooks`
- Update imports of hooks accordingly

### CODE REVIEW

**Review by NooBat — COMMENTED** [review]
Why are we using named exports instead of default exports here?

**Comment by dlnanh85** [comment]
> Why are we using named exports instead of default exports here?

As I tried to implement the `index.ts`, I find that default exports cause the syntax inside `index.ts` more roburst, so I used the named exports for a shorter code. But now when you mention it, and I find my decision unreasonable, which also ignored the point of named and default export.
I have updated the default export. Thank you.

**Review by NooBat — DISMISSED** [review]
Cheers 🎉

**Review by NooBat — APPROVED** [review]
Cheers 🎉

**Pull request merged**
